### ISSUE TITLE
`require_player_movement` breaks `run_rules_on_level_start` and `realtime_interval`

### ISSUE THREAD

**Issue by icecoldtofu** [Auroriax/PuzzleScript#3]
`require_player_movement` should be disregarded during realtime ticks and on level start.

Vanilla: https://www.puzzlescript.net/editor.html?hack=e1862a4bdcc701d11b9100813bac50d0

Plus: https://auroriax.github.io/PuzzleScript/editor.html?hack=e1862a4bdcc701d11b9100813bac50d0

**Comment by Auroriax** [comment]
Should be fixed now, keeping it open as a reminder for myself to double check where this bug originated from (probably PuzzleClick) and add a pull request there.

If you find any more bugs, feel free to keep reporting them!

**Comment by Auroriax** [comment]
Could not find the original origin of the bug, so I'm pretty sure it was caused by me dun goofing a merge. Closing!
